// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: voip.proto
package red.tel.chat.generated_protobuf;

import android.os.Parcelable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class AudioSample extends AndroidMessage<AudioSample, AudioSample.Builder> {
  public static final ProtoAdapter<AudioSample> ADAPTER = new ProtoAdapter_AudioSample();

  public static final Parcelable.Creator<AudioSample> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "red.tel.chat.generated_protobuf.Image#ADAPTER"
  )
  public final Image image;

  public AudioSample(Image image) {
    this(image, ByteString.EMPTY);
  }

  public AudioSample(Image image, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.image = image;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.image = image;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AudioSample)) return false;
    AudioSample o = (AudioSample) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(image, o.image);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (image != null ? image.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (image != null) builder.append(", image=").append(image);
    return builder.replace(0, 2, "AudioSample{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<AudioSample, Builder> {
    public Image image;

    public Builder() {
    }

    public Builder image(Image image) {
      this.image = image;
      return this;
    }

    @Override
    public AudioSample build() {
      return new AudioSample(image, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_AudioSample extends ProtoAdapter<AudioSample> {
    public ProtoAdapter_AudioSample() {
      super(FieldEncoding.LENGTH_DELIMITED, AudioSample.class);
    }

    @Override
    public int encodedSize(AudioSample value) {
      return Image.ADAPTER.encodedSizeWithTag(1, value.image)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, AudioSample value) throws IOException {
      Image.ADAPTER.encodeWithTag(writer, 1, value.image);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public AudioSample decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.image(Image.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public AudioSample redact(AudioSample value) {
      Builder builder = value.newBuilder();
      if (builder.image != null) builder.image = Image.ADAPTER.redact(builder.image);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
