// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: voip.proto
package red.tel.chat.generated_protobuf;

import android.os.Parcelable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class Av extends AndroidMessage<Av, Av.Builder> {
  public static final ProtoAdapter<Av> ADAPTER = new ProtoAdapter_Av();

  public static final Parcelable.Creator<Av> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "red.tel.chat.generated_protobuf.VideoSample#ADAPTER"
  )
  public final VideoSample video;

  @WireField(
      tag = 2,
      adapter = "red.tel.chat.generated_protobuf.AudioSample#ADAPTER"
  )
  public final AudioSample audio;

  public Av(VideoSample video, AudioSample audio) {
    this(video, audio, ByteString.EMPTY);
  }

  public Av(VideoSample video, AudioSample audio, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.video = video;
    this.audio = audio;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.video = video;
    builder.audio = audio;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Av)) return false;
    Av o = (Av) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(video, o.video)
        && Internal.equals(audio, o.audio);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (video != null ? video.hashCode() : 0);
      result = result * 37 + (audio != null ? audio.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (video != null) builder.append(", video=").append(video);
    if (audio != null) builder.append(", audio=").append(audio);
    return builder.replace(0, 2, "Av{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Av, Builder> {
    public VideoSample video;

    public AudioSample audio;

    public Builder() {
    }

    public Builder video(VideoSample video) {
      this.video = video;
      return this;
    }

    public Builder audio(AudioSample audio) {
      this.audio = audio;
      return this;
    }

    @Override
    public Av build() {
      return new Av(video, audio, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Av extends ProtoAdapter<Av> {
    public ProtoAdapter_Av() {
      super(FieldEncoding.LENGTH_DELIMITED, Av.class);
    }

    @Override
    public int encodedSize(Av value) {
      return VideoSample.ADAPTER.encodedSizeWithTag(1, value.video)
          + AudioSample.ADAPTER.encodedSizeWithTag(2, value.audio)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Av value) throws IOException {
      VideoSample.ADAPTER.encodeWithTag(writer, 1, value.video);
      AudioSample.ADAPTER.encodeWithTag(writer, 2, value.audio);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Av decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.video(VideoSample.ADAPTER.decode(reader)); break;
          case 2: builder.audio(AudioSample.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Av redact(Av value) {
      Builder builder = value.newBuilder();
      if (builder.video != null) builder.video = VideoSample.ADAPTER.redact(builder.video);
      if (builder.audio != null) builder.audio = AudioSample.ADAPTER.redact(builder.audio);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
