// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: voip.proto
package red.tel.chat.generated_protobuf;

import android.os.Parcelable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class AVSession extends AndroidMessage<AVSession, AVSession.Builder> {
  public static final ProtoAdapter<AVSession> ADAPTER = new ProtoAdapter_AVSession();

  public static final Parcelable.Creator<AVSession> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_SID = "";

  public static final String DEFAULT_GID = "";

  public static final Boolean DEFAULT_ACTIVE = false;

  public static final ByteString DEFAULT_DATA = ByteString.EMPTY;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String sid;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String gid;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean active;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES"
  )
  public final ByteString data;

  public AVSession(String sid, String gid, Boolean active, ByteString data) {
    this(sid, gid, active, data, ByteString.EMPTY);
  }

  public AVSession(String sid, String gid, Boolean active, ByteString data,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.sid = sid;
    this.gid = gid;
    this.active = active;
    this.data = data;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.sid = sid;
    builder.gid = gid;
    builder.active = active;
    builder.data = data;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AVSession)) return false;
    AVSession o = (AVSession) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(sid, o.sid)
        && Internal.equals(gid, o.gid)
        && Internal.equals(active, o.active)
        && Internal.equals(data, o.data);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (sid != null ? sid.hashCode() : 0);
      result = result * 37 + (gid != null ? gid.hashCode() : 0);
      result = result * 37 + (active != null ? active.hashCode() : 0);
      result = result * 37 + (data != null ? data.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (sid != null) builder.append(", sid=").append(sid);
    if (gid != null) builder.append(", gid=").append(gid);
    if (active != null) builder.append(", active=").append(active);
    if (data != null) builder.append(", data=").append(data);
    return builder.replace(0, 2, "AVSession{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<AVSession, Builder> {
    public String sid;

    public String gid;

    public Boolean active;

    public ByteString data;

    public Builder() {
    }

    public Builder sid(String sid) {
      this.sid = sid;
      return this;
    }

    public Builder gid(String gid) {
      this.gid = gid;
      return this;
    }

    public Builder active(Boolean active) {
      this.active = active;
      return this;
    }

    public Builder data(ByteString data) {
      this.data = data;
      return this;
    }

    @Override
    public AVSession build() {
      return new AVSession(sid, gid, active, data, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_AVSession extends ProtoAdapter<AVSession> {
    public ProtoAdapter_AVSession() {
      super(FieldEncoding.LENGTH_DELIMITED, AVSession.class);
    }

    @Override
    public int encodedSize(AVSession value) {
      return ProtoAdapter.STRING.encodedSizeWithTag(1, value.sid)
          + ProtoAdapter.STRING.encodedSizeWithTag(2, value.gid)
          + ProtoAdapter.BOOL.encodedSizeWithTag(3, value.active)
          + ProtoAdapter.BYTES.encodedSizeWithTag(4, value.data)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, AVSession value) throws IOException {
      ProtoAdapter.STRING.encodeWithTag(writer, 1, value.sid);
      ProtoAdapter.STRING.encodeWithTag(writer, 2, value.gid);
      ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.active);
      ProtoAdapter.BYTES.encodeWithTag(writer, 4, value.data);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public AVSession decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.sid(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.gid(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.active(ProtoAdapter.BOOL.decode(reader)); break;
          case 4: builder.data(ProtoAdapter.BYTES.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public AVSession redact(AVSession value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
