// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: wire.proto
package red.tel.chat.generated_protobuf;

import android.os.Parcelable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class Login extends AndroidMessage<Login, Login.Builder> {
  public static final ProtoAdapter<Login> ADAPTER = new ProtoAdapter_Login();

  public static final Parcelable.Creator<Login> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_TYPE = 0;

  public static final String DEFAULT_USERNAME = "";

  public static final String DEFAULT_AUTHENTOKEN = "";

  public static final String DEFAULT_DEVICETOKEN = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer type;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String userName;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String authenToken;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String deviceToken;

  public Login(Integer type, String userName, String authenToken, String deviceToken) {
    this(type, userName, authenToken, deviceToken, ByteString.EMPTY);
  }

  public Login(Integer type, String userName, String authenToken, String deviceToken,
      ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.type = type;
    this.userName = userName;
    this.authenToken = authenToken;
    this.deviceToken = deviceToken;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.type = type;
    builder.userName = userName;
    builder.authenToken = authenToken;
    builder.deviceToken = deviceToken;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Login)) return false;
    Login o = (Login) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(type, o.type)
        && Internal.equals(userName, o.userName)
        && Internal.equals(authenToken, o.authenToken)
        && Internal.equals(deviceToken, o.deviceToken);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (type != null ? type.hashCode() : 0);
      result = result * 37 + (userName != null ? userName.hashCode() : 0);
      result = result * 37 + (authenToken != null ? authenToken.hashCode() : 0);
      result = result * 37 + (deviceToken != null ? deviceToken.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (type != null) builder.append(", type=").append(type);
    if (userName != null) builder.append(", userName=").append(userName);
    if (authenToken != null) builder.append(", authenToken=").append(authenToken);
    if (deviceToken != null) builder.append(", deviceToken=").append(deviceToken);
    return builder.replace(0, 2, "Login{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Login, Builder> {
    public Integer type;

    public String userName;

    public String authenToken;

    public String deviceToken;

    public Builder() {
    }

    public Builder type(Integer type) {
      this.type = type;
      return this;
    }

    public Builder userName(String userName) {
      this.userName = userName;
      return this;
    }

    public Builder authenToken(String authenToken) {
      this.authenToken = authenToken;
      return this;
    }

    public Builder deviceToken(String deviceToken) {
      this.deviceToken = deviceToken;
      return this;
    }

    @Override
    public Login build() {
      return new Login(type, userName, authenToken, deviceToken, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Login extends ProtoAdapter<Login> {
    public ProtoAdapter_Login() {
      super(FieldEncoding.LENGTH_DELIMITED, Login.class);
    }

    @Override
    public int encodedSize(Login value) {
      return ProtoAdapter.UINT32.encodedSizeWithTag(1, value.type)
          + ProtoAdapter.STRING.encodedSizeWithTag(2, value.userName)
          + ProtoAdapter.STRING.encodedSizeWithTag(3, value.authenToken)
          + ProtoAdapter.STRING.encodedSizeWithTag(4, value.deviceToken)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Login value) throws IOException {
      ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.type);
      ProtoAdapter.STRING.encodeWithTag(writer, 2, value.userName);
      ProtoAdapter.STRING.encodeWithTag(writer, 3, value.authenToken);
      ProtoAdapter.STRING.encodeWithTag(writer, 4, value.deviceToken);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Login decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.type(ProtoAdapter.UINT32.decode(reader)); break;
          case 2: builder.userName(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.authenToken(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.deviceToken(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Login redact(Login value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
