// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: wire.proto
package red.tel.chat.generated_protobuf;

import android.os.Parcelable;
import com.squareup.wire.AndroidMessage;
import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class PlainText extends AndroidMessage<PlainText, PlainText.Builder> {
  public static final ProtoAdapter<PlainText> ADAPTER = new ProtoAdapter_PlainText();

  public static final Parcelable.Creator<PlainText> CREATOR = AndroidMessage.newCreator(ADAPTER);

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_TYPE = 0;

  public static final String DEFAULT_CONTENT = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer type;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String content;

  public PlainText(Integer type, String content) {
    this(type, content, ByteString.EMPTY);
  }

  public PlainText(Integer type, String content, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.type = type;
    this.content = content;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.type = type;
    builder.content = content;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PlainText)) return false;
    PlainText o = (PlainText) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(type, o.type)
        && Internal.equals(content, o.content);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (type != null ? type.hashCode() : 0);
      result = result * 37 + (content != null ? content.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (type != null) builder.append(", type=").append(type);
    if (content != null) builder.append(", content=").append(content);
    return builder.replace(0, 2, "PlainText{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<PlainText, Builder> {
    public Integer type;

    public String content;

    public Builder() {
    }

    public Builder type(Integer type) {
      this.type = type;
      return this;
    }

    public Builder content(String content) {
      this.content = content;
      return this;
    }

    @Override
    public PlainText build() {
      return new PlainText(type, content, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_PlainText extends ProtoAdapter<PlainText> {
    public ProtoAdapter_PlainText() {
      super(FieldEncoding.LENGTH_DELIMITED, PlainText.class);
    }

    @Override
    public int encodedSize(PlainText value) {
      return ProtoAdapter.UINT32.encodedSizeWithTag(1, value.type)
          + ProtoAdapter.STRING.encodedSizeWithTag(2, value.content)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, PlainText value) throws IOException {
      ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.type);
      ProtoAdapter.STRING.encodeWithTag(writer, 2, value.content);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public PlainText decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.type(ProtoAdapter.UINT32.decode(reader)); break;
          case 2: builder.content(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public PlainText redact(PlainText value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
