platform :osx, '10.12'

target 'Chat' do
  use_frameworks!
  pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream', :branch => 'swift3', :inhibit_warnings => true
  pod 'ProtocolBuffers-Swift', :inhibit_warnings => true
  pod 'themis', :podspec => 'https://raw.githubusercontent.com/cossacklabs/themis/master/themis.podspec', :inhibit_warnings => true
  pod 'JWTDecode'
  pod 'ADAL'
  pod 'NXOAuth2Client'
end

# Only work pod 1.3.1 or later
pre_install do |installer|
	# workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
	Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.12'
    end
  end
end
