# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Chat' do
  use_frameworks!
  pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream', :branch => 'swift3', :inhibit_warnings => true
  pod 'ProtocolBuffers-Swift', :inhibit_warnings => true
  pod 'themis', :inhibit_warnings => true
  pod 'SlackTextViewController', :inhibit_warnings => true
  pod 'Toast-Swift', '~> 2.0.0'
  pod 'JWTDecode'
end

# Only work pod 1.3.1 or later
pre_install do |installer|
	# workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
	Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end